### ISSUE TITLE
cue files are rescanned at every run

### ISSUE THREAD

**Issue by grasshide** [CDrummond/bliss-analyser#2]
I saw that cue files are re-scanned every time I scan my library.

Otherwise great plugin! I really enjoy it! Thanks for making this available.

**Comment by CDrummond** [comment]
Don't actually have any CUE files. Anyhow, I've just updated the code. Any chance you can build this and confirm if fixed?

**Comment by grasshide** [comment]
Thank you, works fine now ;)

**Comment by CDrummond** [comment]
Thanks for the confirmation.
