### ISSUE TITLE
Solution: Github Action not working for Linux ARM 

### ISSUE THREAD

**Issue by chincheta0815** [CDrummond/bliss-analyser#3]
Hej theren,

if you remove the "sudo"s and add a "apt-get install cargo ..." to this line here here: https://github.com/CDrummond/bliss-analyser/blob/f023faa336dabb3bbdd8c682661f8db979378134/.github/workflows/build.yml#L18

The action will stop a little bit later with 
Updating crates.io index
[73](https://github.com/chincheta0815/bliss-analyser/runs/6918399634?check_suite_focus=true#step:3:74)
  /home/runner/work/_actions/uraimo/run-on-arch-action/v2.2.0/src/run-on-arch-commands.sh: line 4:    12 Killed                  cargo build --release
[74](https://github.com/chincheta0815/bliss-analyser/runs/6918399634?check_suite_focus=true#step:3:75)
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.2.0/src/run-on-arch.sh' failed with exit code 137

**Comment by CDrummond** [comment]
Sorry, are you saying:

```
 run: sudo apt-get update && sudo apt-get install build-essential yasm libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libswresample-dev libfftw3-dev ffmpeg -y 
```
Should be:
```
 run: apt-get update && apt-get install cargo build-essential yasm libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libswresample-dev libfftw3-dev ffmpeg -y 
```
???

Does this work? As the rest of you message states it fails later.

**Comment by CDrummond** [comment]
Also, that line builds for x86 - nothing to do with ARM.

**Comment by chincheta0815** [comment]
Sorry, for the confusion.
So far your script (as is) stops with an error that there is sudo missing...

This refers to a not installed sudo in the image.
Removing sudo makes the docker image stop with a message that there is no cargo found.

Summed up, when you use 
"run: apt-get update && apt-get install cargo ..."
the docker script runs way further building the image (at least).
This line will also work with all other platforms without "sudo". I think all other platforms have a "sudo", thus making it work...

Once the image is build there is a new issue, which is something real odd and I cannot solve it.

The command "cargo build --release" invokes a "cargo update".
The latter crashes with:
```
Updating crates.io index
[73](https://github.com/chincheta0815/bliss-analyser/runs/6918399634?check_suite_focus=true#step:3:74)
/home/runner/work/_actions/uraimo/run-on-arch-action/v2.2.0/src/run-on-arch-commands.sh: line 4: 12 Killed cargo build --release
[74](https://github.com/chincheta0815/bliss-analyser/runs/6918399634?check_suite_focus=true#step:3:75)
Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.2.0/src/run-on-arch.sh' failed with exit code 137
```

The part "run-on-arch-commands.sh: line 4: 12 Killed cargo build --release" shows that. But I do not know what that means, as "... line 4: 12 ..." is odd to me.

**Comment by CDrummond** [comment]
Which branch are you referring to? As I looked into ARM builds in the `linux-arm` branch - but these builds fail. But the line you point to is from `master` - which does not build for ARM.

**Comment by chincheta0815** [comment]
For the "apt-get" line is refer to the linux-arm branch (see first cooment in this issue).

The build fails then, but later with the message concerning cargo.

My point is that I wanted to help getting aarch64 to build...

**Comment by CDrummond** [comment]
Sorry, did not mean to sound negative - I **really** appreciate any help. This is not an area I know much about. The arm build code is sort-of copied from Spotty.

I was confused as your line had "run: sudo apt-get update" - but this line does not exist for the ARM section. Anyhow I have applied your change to that I assume is the correct line. But, as you stated, build still fails.

**Comment by chincheta0815** [comment]
Now the`linux-arm` stops in your runner as mine did...

Without installing cargo via apt-get it would complain, that there was no command named "cargo".

The error that is shown now is one I do not know how to debug as the error message is cryptic/odd/not clear... at least to me.

**Comment by chincheta0815** [comment]
no problem. all these lines are quite similar so probably I just got the wrong line...

Anyway, the most important thing is: the run crashes later with a different message.

**Comment by chincheta0815** [comment]
I did some testing in a more "open" and "readable" docker process. This docker process is based on "https://github.com/michaelherger/librespot"

This then helps a lot in debugging showing, that there is something wrong when compiling ffmpeg-sys-next...

For getting further I hat to add additional ffmpeg packages ( the ones for arm64 and armhf) plus some more.
Which ones can be seen here: https://github.com/chincheta0815/bliss-analyser/blob/linux-arm/docker/Dockerfile

Concerning the following cargo build I got further with the things in this file: https://github.com/chincheta0815/bliss-analyser/blob/linux-arm/docker/docker-build.sh
There were some env vars needed esp. for pkg-config..

I really do not know why the system does not set them on its own...

Anyway, there are still some issues, but I hope this helps.

**Comment by chincheta0815** [comment]
The two files in "https://github.com/chincheta0815/bliss-analyser/tree/linux-arm/docker" plus the workflow in "https://github.com/chincheta0815/bliss-analyser/tree/linux-arm/.github/workflows" make it compile for arm.

What I did not get to work is a musl build for x86 and x64. But I actually do not know if that is necessary.

**Comment by CDrummond** [comment]
It works!!!!! Thanks so much for your help!

**Comment by CDrummond** [comment]
Changes merged into master, so closing. Once again thank you very much, this would not have been accomplished without your help.

I've uploaded a 0.2.1 Linux ARM package. This contains a shell script to execute the correct version.

**Comment by chincheta0815** [comment]
Your're welcome. I also appreciate your work!

Just a comment/remarke/question concerning the analyser: As you mentioned you do not want to touch the music files by adding tags. 

Otherwise it makes sense to give each file the bliss info via tags: Once you add the replay gain tags one could also add the bliss tags. Afterwards you could then write these tags to bliss.db by just "copying" them into the db. If there are none just do what it does now plus probably add them again...

So what I am thinking of as a proposal:
Make  
    (1) the tag adding optional (e.g. APE as replaygain does it),
    (2) while scanning (optionally) check for tags and add these without rescan to bliss.db
    (3) when doing the first two points it might be also worth thinking of adding the tag info to the overall lms database making a second bliss.db oboslete. This could also be optional as it would cost a wipe/rescan of the lms db.
In general, one can avoid to do this tremendous scan/analyse effort plus doubling info (e.g. file path in two dbs...)

Does that make also sense to you?

**Comment by CDrummond** [comment]
I can see the advantage of saving the results in file-tags, it's just not been a high priority for me - I don't really want to re-write all my files. I've raised issue #4 so that this is not forgotten.

Problem with not using bliss.db is that this then becomes LMS specific, which it currently is not. The mixer executable would also then need to use the LMS db, which to be fair is not much of an issue (as its invoked via LMS). To be honest the mixer could be 100% written in perl, and use LMS's DB, its just that I'm not overly comfortable writing perl.

The reason for the separate DB file, etc, is because I analyse on my laptop then upload the results to my LMS on a Pi4.

**Comment by chincheta0815** [comment]
> I can see the advantage of saving the results in file-tags, it's just not been a high priority for me - I don't really want to re-write all my files. I've raised issue #4 so that this is not forgotten.
> 
Thank you very much.

> Problem with not using bliss.db is that this then becomes LMS specific, which it currently is not. The mixer executable would also then need to use the LMS db, which to be fair is not much of an issue (as its invoked via LMS). To be honest the mixer could be 100% written in perl, and use LMS's DB, its just that I'm not overly comfortable writing perl.
Wow! I just saw your Pearl and your Rust code. You are quite good, at least better than I am. Usually I say, okay there is the algorithm in one language I can do it in another. But what you did is far beyond my knowledge.

> The reason for the separate DB file, etc, is because I analyse on my laptop then upload the results to my LMS on a Pi4.
That's what I read in the forum and makes totally sense. I one has the time to do it on a raspi, make that option via command line arg could be a solution.
