### ISSUE TITLE
Add more weighting options to euclidean distance calculation

### ISSUE THREAD

**Issue by chourmovs** [CDrummond/bliss-analyser#6]
I 'm not sure  if this has to be done "bliss plugin side" or "bliss analysis side", but this could be a nice to have to get more tweaking ability in our mixes, by playing on weight/influence of tempo, timbre, chroma and loudness in the result

taken from https://lelele.io/bliss.html
_While the euclidean distance (each numeric feature counts for the same amount as the other in the distance) provides very satisfactory results, experimenting with metric learning, or simply adjusting the distance coefficients could improve your experience, so don't hesitate to do so!_

I love your plugin otherwise, please continue the good work

**Comment by CDrummond** [comment]
Moved to [bliss-mixer](https://github.com/CDrummond/bliss-mixer/issues/6) - as its the mixer that will do this weighting.
